SRC +=	$(SRC_DIR)/lib/tinyprintf/tinyprintf.c

SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/tusb.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/typec/usbc.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/class/cdc/cdc_host.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/class/hid/hid_host.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/class/msc/msc_host.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/host/hub.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/host/usbh.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/common/tusb_fifo.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/portable/ehci/ehci.c
SRC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src/portable/ohci/ohci.c

INC +=	$(SRC_DIR)/lib/tinyprintf
INC +=	$(SRC_DIR)/lib/hftrx_tinyusb_fork/src