#SRC +=	$(SRC_DIR)/aw_lib/cache-c906.c
SRC +=	$(SRC_DIR)/aw_lib/ccu.c
SRC +=	$(SRC_DIR)/aw_lib/de.c
SRC +=	$(SRC_DIR)/aw_lib/de_scaler_table.c
#SRC +=	$(SRC_DIR)/aw_lib/dmac.c
SRC +=	$(SRC_DIR)/aw_lib/gpio.c
SRC +=	$(SRC_DIR)/aw_lib/gr.c
SRC +=	$(SRC_DIR)/aw_lib/irq.c	
SRC +=	$(SRC_DIR)/aw_lib/led.c
#SRC +=	$(SRC_DIR)/aw_lib/smhc.c
SRC +=	$(SRC_DIR)/aw_lib/tcon_lcd.c
#SRC +=	$(SRC_DIR)/aw_lib/timer.c
SRC +=	$(SRC_DIR)/aw_lib/twi.c
SRC +=	$(SRC_DIR)/aw_lib/uart.c
SRC +=	$(SRC_DIR)/aw_lib/usb.c
SRC +=	$(SRC_DIR)/aw_lib/dsi.c

INC +=	$(SRC_DIR)/aw_lib