SRC +=	$(SRC_DIR)/components/usb_task.c
SRC +=	$(SRC_DIR)/components/dispaly_task.c
SRC +=	$(SRC_DIR)/components/console_task.c
SRC +=	$(SRC_DIR)/components/doom_task.c
SRC +=	$(SRC_DIR)/components/tlsf.c

INC +=	$(SRC_DIR)/components