SRC +=	$(SRC_DIR)/application/main.c
SRC +=	$(SRC_DIR)/application/hid_app.c
SRC +=	$(SRC_DIR)/application/console_task.c
SRC +=	$(SRC_DIR)/application/doom/doom_task.c
SRC +=	$(SRC_DIR)/application/doom/m_fixed.c
SRC +=	$(SRC_DIR)/application/doom/i_video.c

INC +=	$(SRC_DIR)/application/doom/
INC +=	$(SRC_DIR)/application

